[build]
  command = "npm run build"
  publish = ".next"

[[redirects]]
  from = "/favicon.ico"
  to = "/favicon.ico"
  status = 200

[[redirects]]
  from = "/api/cart"
  to = "/api/cart"
  status = 200

[[redirects]]
  from = "/api/products"
  to = "/api/products"
  status = 200

[[redirects]]
  from = "/api/products/:id"
  to = "/api/products/[id]"
  status = 200

[[redirects]]
  from = "/api/orders"
  to = "/api/orders"
  status = 200

[[plugins]]
  package = "@netlify/plugin-nextjs"
