[build]
  command = "npm run build"
  publish = ".next" # Assurez-vous que c'est bien le répertoire de publication de votre build Next.js
  functions = "netlify/functions" # Chemin vers le répertoire contenant vos fonctions Netlify

[[redirects]]
  from = "/favicon.ico"
  to = "/favicon.ico"
  status = 200

[[redirects]]
  from = "/api/cart"
  to = "/.netlify/functions/cart" # Assurez-vous que vos fonctions sont à cet endroit
  status = 200

[[redirects]]
  from = "/api/products"
  to = "/.netlify/functions/products/index" # Assurez-vous que vos fonctions sont à cet endroit
  status = 200

[[redirects]]
  from = "/api/products/:id"
  to = "/.netlify/functions/products/[id]" # Utilisez le nom du fichier dynamique avec crochets
  status = 200

[[redirects]]
  from = "/api/orders"
  to = "/.netlify/functions/orders" # Assurez-vous que vos fonctions sont à cet endroit
  status = 200

[[plugins]]
  package = "@netlify/plugin-nextjs"
