import Head from 'next/head';
import Image from 'next/image';
import { Box, Text } from '@chakra-ui/react';

export default function Home() {
  return (
    <Box>
      <Head>
        <title>My Next.js App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Box textAlign="center" color="white" bg="teal.500" p={4}>
        <Text fontSize="4xl">L'attention à portée de main</Text>
        <Text fontSize="xl">Votre slogan ici</Text>
      </Box>

      <main>
        <Box className="sectionPrincipale" p={4}>
          {/* Contenu de la section principale */}
        </Box>
        
        <Box className="newSection" display="flex" justifyContent="space-around" p={4}>
          <Box className="card" bg="white" borderWidth={1} borderRadius="md" p={4} textAlign="center">
            <Image src="/product1.jpg" alt="Product 1" width={200} height={200} />
            <Text as="h3" fontSize="xl" mt={2}>Product 1</Text>
            <Text mt={2}>This is the description for Product 1.</Text>
            <Text className="price" mt={2} fontSize="lg">$10.00</Text>
          </Box>

          <Box className="card" bg="white" borderWidth={1} borderRadius="md" p={4} textAlign="center">
            <Image src="/product2.jpg" alt="Product 2" width={200} height={200} />
            <Text as="h3" fontSize="xl" mt={2}>Product 2</Text>
            <Text mt={2}>This is the description for Product 2.</Text>
            <Text className="price" mt={2} fontSize="lg">$20.00</Text>
          </Box>

          <Box className="card" bg="white" borderWidth={1} borderRadius="md" p={4} textAlign="center">
            <Image src="/product3.jpg" alt="Product 3" width={200} height={200} />
            <Text as="h3" fontSize="xl" mt={2}>Product 3</Text>
            <Text mt={2}>This is the description for Product 3.</Text>
            <Text className="price" mt={2} fontSize="lg">$30.00</Text>
          </Box>
        </Box>
      </main>
    </Box>
  );
}
