import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/globals.css';

export default function Home() {
  return (
    <div>
      <Head>
        <title>My Next.js App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header>
        <h1 style={{ color: 'white', textAlign: 'center' }}>L'attention à portée de main</h1>
        <p style={{ color: 'white', textAlign: 'center' }}>Votre slogan ici</p>
      </header>

      <main>
        <section className="sectionPrincipale"></section>
        <section className="newSection">
          <div className="card">
            <Image src="/product1.jpg" alt="Product 1" width={200} height={200} />
            <h3>Product 1</h3>
            <p>This is the description for Product 1.</p>
            <p className="price">$10.00</p>
          </div>
          <div className="card">
            <Image src="/product2.jpg" alt="Product 2" width={200} height={200} />
            <h3>Product 2</h3>
            <p>This is the description for Product 2.</p>
            <p className="price">$20.00</p>
          </div>
          <div className="card">
            <Image src="/product3.jpg" alt="Product 3" width={200} height={200} />
            <h3>Product 3</h3>
            <p>This is the description for Product 3.</p>
            <p className="price">$30.00</p>
          </div>
        </section>
      </main>
    </div>
  );
}

